theme: jekyll-theme-slate
title: Saved Keystrokes
description: Gathering knowledge and saving keystrokes one at a time…

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "default.html"